version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sequelize
    versions:
    - 6.5.0
    - 6.5.1
    - 6.6.1
  - dependency-name: swagger-jsdoc
    versions:
    - 6.0.1
    - 6.0.2
    - 6.0.5
    - 6.0.6
    - 6.0.7
    - 6.0.8
    - 6.0.9
  - dependency-name: nodemailer
    versions:
    - 6.4.17
    - 6.4.18
    - 6.5.0
